cfg:
  data_generation_params:
    lane_params:
      max_num_crosswalks: 20
      max_num_lanes: 30
      max_points_per_crosswalk: 20
      max_points_per_lane: 20
      max_retrieval_distance_m: 50
    max_agents_distance: 50
    other_agents_num: 50
  dataset_path: /home/alexay/lyft-attn/DATASET_DIR/
  format_version: 7
  model_params:
    agent_num_trajectories: 3
    cost_prob_coeff: 0.1
    disable_lane_boundaries: false
    disable_map: false
    disable_other_agents: false
    future_num_frames: 50
    history_num_frames_agents: 19
    history_num_frames_ego: 19
    perturbation_min_displacement_m: 1.2
    perturbation_probability: 1.0
    render_ego_history: false
    step_time: 0.1
    use_gaussian_perturbation: false
    use_perturbation: false
    weights_scaling:
    - 1.0
    - 1.0
    - 1.0
  raster_params:
    dataset_meta_key: meta.json
    disable_traffic_light_faces: false
    ego_center:
    - 0.25
    - 0.5
    filter_agents_threshold: 0.5
    map_type: py_semantic
    pixel_size:
    - 0.5
    - 0.5
    raster_size:
    - 224
    - 224
    satellite_map_key: aerial_map/aerial_map.png
    semantic_map_key: semantic_map/semantic_map.pb
    set_origin_to_bottom: false
  test_data_loader:
    batch_size: 64
    key: scenes/test.zarr
    num_workers: 8
    shuffle: false
  train_data_loader:
    batch_size: 16
    key: scenes/train.zarr
    num_workers: 4
    shuffle: true
  train_params:
    checkpoint_every_n_epochs: 2
    eval_every_n_epochs: 2
    max_num_steps: 1000
    num_epochs: 6
  val_data_loader:
    batch_size: 64
    key: scenes/validate.zarr
    num_workers: 8
    shuffle: false
config: !!python/object:config.GPTConfig
  batch_size: 8
  bias: true
  block_size: 1024
  dataset_path: /workspace/DATASET_EDITED
  device: cuda:0
  dropout: 0.0
  max_epochs: 10
  n_emb: 12
  n_head: 12
  n_layer: 3
  n_obj: 161
  n_t: 20
  num_workers: 16
  output_size: 303
  vocab_size: 50304
